In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv(r"C:\Users\A I TECH\Downloads\Linear_regression_algorithim\student_salary.csv")
df.head()

   cgpa   iq  salary
0  2.75  117   66543
1  3.90   85   73459
2  3.46  103   75100
3  3.20   86   66748
4  2.31  137   62117

In [7]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [8]:
X

     cgpa   iq
0    2.75  117
1    3.90   85
2    3.46  103
3    3.20   86
4    2.31  137
..    ...  ...
145  2.07   92
146  3.22  111
147  3.01  111
148  2.10  118
149  2.56  105

[150 rows x 2 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)